<?php include 'blocks/header.phtml'; ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                <form action="/urls" method="post" class="row" reqired>
                    <div class="col-8">
                        <input type="text" name="data[url]" value="" class="form-control form-control-lg <?php if (isset($errors)): ?>is-invalid<?php endif ?>" placeholder="https://www.example.com">
                    </div>
<?php if (isset($errors)): ?>
    <?php foreach ($errors as $error): ?>
                        <div class="invalid-feedback">
        <?php htmlspecialchars($error) ?>
                        </div>
    <?php endforeach ?>
<?php endif ?>
                    <div class="col-2">
                        <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

<?php include 'blocks/footer.phtml'; ?>